#!/usr/bin/env bash

# Scheduler header notes:
# - Keep sections ordered as SLURM -> UGE -> PBS across entrypoints.
# - Update job name, CPU count, memory, walltime, log paths, and array size together.
# - UGE resources default to SHIROKANE AGE; SLURM/PBS site-specific lines remain examples.

# SLURM
# Common parameters: job name, cores per task, memory per core, walltime, log files, and working directory.
#SBATCH -J gg_transcriptome_generation
#SBATCH -c 4
#SBATCH --mem-per-cpu=32G
#SBATCH -t 14-00:00:00
#SBATCH --output=gg_transcriptome_generation_entrypoint.sh_%A_%a.out
#SBATCH --error=gg_transcriptome_generation_entrypoint.sh_%A_%a.err
#SBATCH --chdir=.
#SBATCH --ignore-pbs
# Array example for array-aware entrypoints.
#SBATCH -a 1
# Site-specific partition example.
#SBATCH -p epyc,rome,medium
# Optional notifications and single-node examples.
##SBATCH --mail-type=ALL
##SBATCH --mail-user=<aaa@bbb.com>

## UGE
# SHIROKANE AGE defaults: shell, working directory, slot count, memory per slot, and ljob.
#$ -S /bin/bash
#$ -cwd
#$ -pe def_slot 4
#$ -l s_vmem=32G
#$ -l ljob
# Array example for array-aware entrypoints.
#$ -t 1

## PBS
# Common parameters: shell, CPU count, total memory, and exported environment.
#PBS -S /bin/bash
#PBS -l ncpus=4
#PBS -l mem=128G
# Array example for array-aware entrypoints.
#PBS -J 1
# Site-specific queue example.
#PBS -q small
#PBS -V

# Number of parallel batch jobs ("-t 1-N" in SGE or "--array 1-N" in SLURM):
# N = Number of directories in workspace/input/species_rnaseq for mode_transcriptome_assembly=fastq
# N = Number of files in workspace/input/query_sra_id for mode_transcriptome_assembly=sraid
# N = Number of files in workspace/input/amalgkit_metadata for mode_transcriptome_assembly=metadata
# In many cases, 4 cores and s_vmem=16G (=64G) worked well in per-SRA Trinity assembly.
# Increase per-core RAM to 32G if Trinity fails.

set -euo pipefail

echo "$(date): Starting"

# Resolve workflow paths for local and scheduler-spooled execution.
gg_bootstrap_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
gg_bootstrap_checked_bases=""
for gg_bootstrap_base in \
  "${SLURM_SUBMIT_DIR:-}" \
  "${PBS_O_WORKDIR:-}" \
  "${PWD:-}" \
  "${gg_bootstrap_script_dir}"
do
  [[ -n "${gg_bootstrap_base}" ]] || continue
  case ":${gg_bootstrap_checked_bases}:" in
    *":${gg_bootstrap_base}:"*) continue ;;
  esac
  gg_bootstrap_checked_bases="${gg_bootstrap_checked_bases:+${gg_bootstrap_checked_bases}:}${gg_bootstrap_base}"
  for bootstrap_path in \
    "${gg_bootstrap_base}/support/gg_entrypoint_bootstrap.sh" \
    "${gg_bootstrap_base}/workflow/support/gg_entrypoint_bootstrap.sh"
  do
    if [[ -s "${bootstrap_path}" ]]; then
      # shellcheck disable=SC1090
      source "${bootstrap_path}"
      break
    fi
  done
  if declare -F gg_entrypoint_initialize >/dev/null 2>&1; then
    break
  fi
done
unset gg_bootstrap_base gg_bootstrap_checked_bases gg_bootstrap_script_dir bootstrap_path
if ! declare -F gg_entrypoint_initialize >/dev/null 2>&1; then
  echo "Failed to locate gg_entrypoint_bootstrap.sh from BASH_SOURCE[0]=${BASH_SOURCE[0]}" >&2
  exit 1
fi
if ! gg_entrypoint_initialize "${BASH_SOURCE[0]}" 1; then
  exit 1
fi
gg_entrypoint_name="gg_transcriptome_generation_entrypoint.sh"

### Start: Modify this block to tailor your analysis ###

# Mode
mode_transcriptome_assembly="${mode_transcriptome_assembly:-auto}" # {"auto", "sraid", "fastq", "metadata"}; input source for transcriptome assembly: sraid reads accession lists in workspace/input/query_sra_id, fastq reads local FASTQ directories in workspace/input/species_rnaseq, metadata reads amalgkit metadata TSVs, and auto selects the single available layout.

# Workflow flags
run_amalgkit_metadata_or_integrate=1 # Metadata retrieval.
run_amalgkit_getfastq=1 # fastq generation from NCBI SRA.
run_assembly=1 # Transcriptome assembly with Trinity, rnaSPAdes, or RNA-Bloom2.
run_longestcds=1 # Longest CDS extraction.
run_longestcds_fx2tab=1 # Sequence stats for longest CDS.
run_longestcds_mmseqs2taxonomy=0 # MMseqs2 taxonomy.
run_longestcds_contamination_removal=0 # Contamination removal.
run_busco_isoforms=1 # BUSCO for transcriptome assembly with isoforms.
run_busco_longest_cds=1 # BUSCO for longest CDS.
run_busco_contamination_removed_longest_cds=0 # BUSCO for contamination-removed longest CDS.
run_assembly_stat=1 # seqkit stat for assembly and CDS files.
run_amalgkit_quant=1 # Expression quantification with amalgkit auto-selected kallisto/oarfish backend.
run_amalgkit_merge=1 # Expression merge of per-run abundance outputs generated by amalgkit quant.
run_multispecies_summary=1 # Multi-species summary.

# Input-download parameters
amalgkit_rrna_filter="yes" # read-level rRNA removal in amalgkit getfastq. Observed to finish for ~4.2 Gbp total / ~14 million reads within a 350G job before contamination filtering; exact peak RAM and elapsed time for this step alone were not logged.
amalgkit_rrna_filter_jobs="${amalgkit_rrna_filter_jobs:-1}" # Maximum number of runs searched for rRNA concurrently. One run still uses all GG_TASK_CPUS internally.
amalgkit_rrna_filter_chunk_spots="${amalgkit_rrna_filter_chunk_spots:-5000000}" # Maximum spots per synchronized MMseqs rRNA query chunk.
amalgkit_rrna_filter_memory_limit="${amalgkit_rrna_filter_memory_limit:-32G}" # MMseqs --split-memory-limit used for SILVA index creation and rRNA searches.
amalgkit_contam_filter="no" # read-level contamination removal in amalgkit getfastq. Rank follows contamination_removal_rank below. Setting yes may require >350G RAM for large private FASTQ inputs (for example, ~4.2 Gbp total, ~14 million reads).
amalgkit_ncbi_metadata_max_concurrency="${amalgkit_ncbi_metadata_max_concurrency:-20}" # Maximum concurrent NCBI Entrez metadata requests across array tasks. Forwarded to amalgkit metadata/getfastq --ncbi_metadata_max_concurrency. Set 0 or auto to disable throttling.
amalgkit_ncbi_download_max_concurrency="${amalgkit_ncbi_download_max_concurrency:-20}" # Maximum concurrent NCBI cloud-object downloads across array tasks. Forwarded to amalgkit getfastq --ncbi_download_max_concurrency. Set 0 or auto to disable throttling.
amalgkit_aws_download_max_concurrency="${amalgkit_aws_download_max_concurrency:-20}" # Maximum concurrent AWS cloud-object downloads across array tasks. Forwarded to amalgkit getfastq --aws_download_max_concurrency. Set 0 or auto to disable throttling.
amalgkit_gcp_download_max_concurrency="${amalgkit_gcp_download_max_concurrency:-20}" # Maximum concurrent GCP cloud-object downloads across array tasks. Forwarded to amalgkit getfastq --gcp_download_max_concurrency. Set 0 or auto to disable throttling.
amalgkit_sra_strategy_query="${amalgkit_sra_strategy_query:-\"RNA-seq\"[Strategy] OR \"EST\"[Strategy] OR \"CLONE\"[Strategy]}" # Entrez strategy clause appended in mode_transcriptome_assembly=sraid; include CLONE so capillary/Sanger cDNA libraries are eligible. Explicit-accession fallback automatically retries without this clause when transcriptomic runs are missed. Set empty to disable strategy filtering.
remove_amalgkit_fastq_after_completion=1 # Delete per-species amalgkit FASTQ files after downstream completion.

# Assembly and quantification parameters
max_assembly_input_fastq_size="30,000,000,000" # Maximum total FASTQ length in bp used for transcriptome assembly.
assembly_method="auto" # {auto,Trinity,rnaSPAdes,RNA-Bloom2}; auto picks rnaSPAdes for short-read metadata and RNA-Bloom2 for detected PacBio/ONT metadata.
protocol_rna_seq="mixed" # {same,mixed}; rnaSPAdes library protocol handling. Use "same" when all FASTQ libraries share the same RNA-seq library/preparation protocol, so GeneGalleon passes them as one rnaSPAdes library group. Use "mixed" when libraries may come from different protocols or samples, so GeneGalleon passes each library separately as a numbered SPAdes/rnaSPAdes library (--s1..--s9 or --pe1..--pe9); if 10 or more mixed libraries are detected, GeneGalleon first keeps only the 9 largest libraries to fit those numbered input slots, then applies max_assembly_input_fastq_size by subsampling reads from the retained libraries when their combined FASTQ length exceeds the cap.
amalgkit_quant_backend="${amalgkit_quant_backend:-auto}" # {auto,kallisto,oarfish}; auto selects kallisto for short-read runs and oarfish for long-read runs.
amalgkit_oarfish_seq_tech="${amalgkit_oarfish_seq_tech:-auto}" # {auto,ont-cdna,ont-drna,pac-bio,pac-bio-hifi}; auto infers long-read subtype from metadata for oarfish.
amalgkit_oarfish_options="${amalgkit_oarfish_options:-}" # Optional extra shell-style option string forwarded to amalgkit quant --oarfish_options.
kallisto_reference="longest_cds" # {species_cds,longest_transcript,longest_cds,contamination_removed_longest_cds}; reference FASTA used for expression quantification, choosing provider CDS, assembled longest transcripts, assembled longest CDS, or contamination-filtered longest CDS.
orf_aggregation_level="i" # {c,g,i,p}; Longest-CDS ORF aggregation level. The value selects how transcript/ORF IDs are trimmed before choosing one representative CDS per group: "p" groups ORFs within the same transcript, "i" groups isoforms within the same gene-level ID, and "g" or "c" use broader upstream ID levels when those levels exist in the assembler output. Lower levels are more aggressive and collapse more sequences; "i" is the default balance. For rnaSPAdes, "c" is not supported because rnaSPAdes transcript IDs do not include a Trinity-style component level.
assembly_cpu_offset=0 # Number of CPU cores reserved from GG_TASK_CPUS before launching the assembler.
assembly_ram_offset=4 # Amount of RAM in GB reserved from GG_MEM_TOTAL_GB before launching the assembler; GG_MEM_TOOL_RESERVE_GB is used if larger.

# Contamination-removal parameters
contamination_removal_rank="domain" # Taxonomic rank for contamination removal. Canonical value is domain; GeneGalleon normalizes tool-specific synonyms automatically.
contamination_removal_target_taxon="${contamination_removal_target_taxon:-}" # Optional NCBI taxon name used as the lineage anchor for contamination removal (for example, Eukaryota when the sample species name is unknown).

### End: Modify this block to tailor your analysis ###

delete_tmp_dir=1 # After this run, delete tmp directory created for each job. Set 0 when debugging.

source "${gg_support_dir}/gg_util.sh" # loading utility functions
# Forward config variables (including external overrides) into container environment.
gg_apply_registered_env_overrides "${gg_entrypoint_name}" "delete_tmp_dir"
forward_config_vars_to_container_env "${gg_entrypoint_name}" "delete_tmp_dir"
if ! gg_entrypoint_prepare_container_runtime 0; then
  exit 1
fi
gg_entrypoint_activate_container_runtime

gg_entrypoint_enter_workspace
gg_runtime_core_script="$(gg_prepare_entrypoint_runtime_snapshot "${gg_entrypoint_name}" "${gg_core_dir}/gg_transcriptome_generation_core.sh")"
gg_run_container_shell_script "${gg_container_image_path}" "${gg_runtime_core_script}"
gg_require_versions_dump "${gg_entrypoint_name}"

echo "$(date): Ending"
