version: 2
updates:
  - package-ecosystem: pip
    directory: /workflow/tests
    schedule:
      interval: weekly
    groups:
      python-test-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: numpy
        versions:
          - ">=2"
      - dependency-name: matplotlib
        versions:
          - ">=3.11"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
