"""Small, reversible descriptions of predictor inputs instead of repeated FASTAs."""
import csv
import gzip
import hashlib
import json
from pathlib import Path

SCHEMA = 1
LOCAL_RECORDS = "local_search_inputs.jsonl.gz"
GENOME_RECORDS = "genome_search_inputs.jsonl.gz"


def sequence_sha(sequence):
    return hashlib.sha256(sequence.encode()).hexdigest()


def local_record(index, window, regions, proteins, sequence):
    seqid, start, end = window
    return {"schema": SCHEMA, "index": index, "seqid": seqid, "start": start, "end": end,
            "region_sha256": sequence_sha(sequence), "queries": [
                {"candidate": r["id"], "donor": r["donor"], "query": r["query"],
                 "protein_sha256": sequence_sha(proteins[r["donor"]][r["query"]])}
                for r in regions]}


def write_record(handle, value):
    handle.write(json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n")


def write_genome_records(directory, regions, representatives, proteins):
    """Record each actual representative once; the separate TSV retains aliases."""
    by_id = {r["id"]: r for r in regions}
    with gzip.open(Path(directory) / GENOME_RECORDS, "wt", compresslevel=1) as handle:
        for candidate, representative in representatives.items():
            if candidate != representative:
                continue
            region = by_id[candidate]
            write_record(handle, {"schema": SCHEMA, "candidate": candidate,
                                  "donor": region["donor"], "query": region["query"],
                                  "protein_sha256": sequence_sha(proteins[region["donor"]][region["query"]])})


def records(path):
    with gzip.open(path, "rt") as handle:
        for line in handle:
            value = json.loads(line)
            if not isinstance(value, dict) or value.get("schema") != SCHEMA:
                raise ValueError("Unknown predictor input record schema")
            yield value


def genome_aliases(directory):
    """Return the exact candidate order used by this worker's fresh genome search."""
    path = Path(directory) / "genome_prediction_query_mapping.tsv"
    with path.open() as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames != ["candidate", "representative"]:
            raise ValueError("Invalid fresh genome-query alias columns")
        result = {}
        for row in reader:
            candidate, representative = row["candidate"], row["representative"]
            if not candidate or not representative or candidate in result or None in row:
                raise ValueError("Invalid or repeated fresh genome-query alias")
            result[candidate] = representative
    if any(result.get(representative) != representative for representative in result.values()):
        raise ValueError("Fresh genome-query aliases lack their original representative")
    return result


def export_inputs(directory, destination, genome, proteins, *, combined=False):
    """Recreate exact predictor FASTAs after the caller verifies frozen sources.

    The caller publishes this new destination only after rechecking its sources.
    Genome indices are deliberately regenerated by the normal predictor rather
    than archived. No source or producer-receipt member is changed here.
    """
    directory, destination = Path(directory), Path(destination)
    if destination.exists():
        raise FileExistsError("Predictor input export destination already exists")
    destination.mkdir(parents=True)
    total = 0
    if combined:
        region_out = (destination / "regions.fa").open("w")
        query_out = (destination / "queries.fa").open("w")
    else:
        region_out = query_out = None
    try:
        path = directory / LOCAL_RECORDS
        if path.exists():
            for row in records(path):
                total += 1
                if type(row.get("index")) is not int or row["index"] != total:
                    raise ValueError("Invalid or reordered local-search window index")
                start, end = row["start"], row["end"]
                if (type(start) is not int or type(end) is not int
                        or not 0 <= start < end <= genome.get_reference_length(row["seqid"])):
                    raise ValueError("Archived local-search window outside genome")
                sequence = genome.fetch(row["seqid"], start, end)
                if sequence_sha(sequence) != row["region_sha256"]:
                    raise ValueError("Regenerated predictor region differs from frozen input")
                target = destination / "intervals" / str(total)
                target.mkdir(parents=True)
                (target / "region.fa").write_text(f">interval\n{sequence}\n")
                with (target / "queries.fa").open("w") as out:
                    for query in row["queries"]:
                        protein = proteins[query["donor"]][query["query"]]
                        if sequence_sha(protein) != query["protein_sha256"]:
                            raise ValueError("Regenerated predictor query differs from frozen input")
                        text = f">{query['candidate']}\n{protein}\n"
                        out.write(text)
                        if combined:
                            query_out.write(text)
                            region_out.write(f">{query['candidate']}\n{sequence}\n")
        path = directory / GENOME_RECORDS
        if path.exists():
            sequences = {} if combined else None
            with (destination / "unresolved.unique.fa").open("w") as out:
                for query in records(path):
                    protein = proteins[query["donor"]][query["query"]]
                    if sequence_sha(protein) != query["protein_sha256"]:
                        raise ValueError("Regenerated genome query differs from frozen input")
                    out.write(f">{query['candidate']}\n{protein}\n")
                    if combined:
                        if query["candidate"] in sequences:
                            raise ValueError("Repeated genome-query representative")
                        sequences[query["candidate"]] = protein
            if combined:
                aliases = genome_aliases(directory)
                if set(aliases.values()) != set(sequences):
                    raise ValueError("Fresh genome aliases differ from archived query bodies")
                with (destination / "unresolved.fa").open("w") as out:
                    for candidate, representative in aliases.items():
                        out.write(f">{candidate}\n{sequences[representative]}\n")
    finally:
        if combined:
            region_out.close()
            query_out.close()
    return {"local_windows": total, "combined_diagnostics": combined}
