# shellcheck shell=bash
# Sourced by gg_transcriptome_generation_core.sh.

task='Longest CDS extraction'
disable_if_no_input_file "run_longestcds" "${file_isoform}"
if [[ (! -s "${file_longestcds}" || ! -s "${file_longestcds_transcript}") && ${run_longestcds} -eq 1 ]]; then
  gg_step_start "${task}"
  ensure_parent_dir "${file_longestcds}"
  ensure_parent_dir "${file_longestcds_transcript}"

  echo "scientific_name: ${sp_ub}"
  if [[ "${effective_assembly_method}" == 'rna-bloom2' ]]; then
    aggregate_expression="\-i[0-9].*"
    if [[ ! -s "${file_corset_clusters}" ]]; then
      echo "Corset cluster assignments were not found for long-read longest CDS extraction: ${file_corset_clusters}. Exiting."
      exit 1
    fi
    python "${gg_support_dir}/rename_rnabloom_transcripts.py" \
      --input-fasta "${file_isoform}" \
      --clusters "${file_corset_clusters}" \
      --species-prefix "${sp_ub}" \
      --output-fasta "${sp_ub}.tmp.renamed.fa"
  else
    if [[ ${orf_aggregation_level} = "p" ]]; then
      aggregate_expression="\.${orf_aggregation_level}[0-9].*"
    else
      aggregate_expression="\-${orf_aggregation_level}[0-9].*"
    fi
  fi
  if [[ ${orf_aggregation_level} == "c" && "${effective_assembly_method}" == "rnaspades" ]]; then
    echo "The aggregation level 'c' is not supported for rnaSPAdes assemblies. Please set 'orf_aggregation_level' to either 'i' or 'g'."
    echo "Exiting"
    exit 1
  fi

  if [[ "${effective_assembly_method}" == 'trinity' ]]; then
    seqkit sort --by-length --reverse --threads "${GG_TASK_CPUS}" "${file_isoform}" |
      sed -e "s/_/-/g" -e "s/^>[[:space:]]*/>${sp_ub}_/" -e "s/TRINITY-//" -e "s/[[:space:]].*//" \
        > "${sp_ub}.tmp.renamed.fa"
  elif [[ "${effective_assembly_method}" == 'rnaspades' ]]; then
    seqkit sort --by-length --reverse --threads "${GG_TASK_CPUS}" "${file_isoform}" |
      sed -e "s/^>.*_g\([0-9]\+\)_i\([0-9]\+\)$/>${sp_ub}_g\1-i\2/" \
        > "${sp_ub}.tmp.renamed.fa"
  elif [[ "${effective_assembly_method}" != 'rna-bloom2' ]]; then
    echo "Invalid value for 'assembly_method'. Please specify one of auto, Trinity, rnaSPAdes, or RNA-Bloom2."
    echo "Exiting."
    exit 1
  fi

  longestcds_tmp="${sp_ub}.tmp.longestcds.raw.fa"
  if ! cdskit longestcds \
    --seqfile "${sp_ub}.tmp.renamed.fa" \
    --outfile "${longestcds_tmp}" \
    --codontable "${genetic_code}" \
    --annotate_seqname no \
    --threads "${GG_TASK_CPUS}"; then
    echo "Error: cdskit longestcds failed."
    echo "Please install a cdskit version that supports the 'longestcds' subcommand."
    exit 1
  fi
  if [[ ! -s "${longestcds_tmp}" ]]; then
    echo "Error: No CDS output generated by cdskit longestcds."
    exit 1
  fi

  seqkit rmdup --by-seq "${longestcds_tmp}" |
    cdskit pad --codontable "${genetic_code}" |
    seqkit sort --by-name --threads "${GG_TASK_CPUS}" |
    cdskit aggregate -x "${aggregate_expression}" \
      > "${sp_ub}.tmp.aggregated.fa"

  awk '/^>/ {sub(/^>/, "", $0); sub(/[[:space:]].*$/, "", $0); sub(/\.p[0-9].*$/, "", $0); print}' \
    "${sp_ub}.tmp.aggregated.fa" > "${sp_ub}.tmp.aggregated.transcript_id.txt"

  if [[ -s "${sp_ub}.tmp.aggregated.fa" && -s "${sp_ub}.tmp.aggregated.transcript_id.txt" ]]; then
    echo "Output file detected for the task: ${task}"
    seqkit grep \
      --threads "${GG_TASK_CPUS}" \
      --pattern-file "${sp_ub}.tmp.aggregated.transcript_id.txt" \
      "${sp_ub}.tmp.renamed.fa" \
      --out-file "${sp_ub}.tmp.longestcds.transcript.fa.gz"
    mv_out "${sp_ub}.tmp.longestcds.transcript.fa.gz" "${file_longestcds_transcript}"
    sed -e "s/[[:space:]].*//" -e "s/${aggregate_expression}//" "${sp_ub}.tmp.aggregated.fa" |
      seqkit seq --threads "${GG_TASK_CPUS}" --out-file "${sp_ub}.tmp.longestcds.fa.gz"
    mv_out "${sp_ub}.tmp.longestcds.fa.gz" "${file_longestcds}"
  else
    echo "Output file not detected for the task: ${task}"
  fi
  echo "$(date): End: ${task}"
else
  gg_step_skip "${task}"
fi

task="seqkit fx2tab for the longest CDS sequences"
invalidate_cached_query_table_if_prefix_mismatch "${file_longestcds_fx2tab}" "${sp_ub}_" "${task}" 1
disable_if_no_input_file "run_longestcds_fx2tab" "${file_longestcds}"
if [[ ! -s "${file_longestcds_fx2tab}" && ${run_longestcds_fx2tab} -eq 1 ]]; then
  gg_step_start "${task}"

  seqkit fx2tab \
    --threads "${GG_TASK_CPUS}" \
    --length \
    --name \
    --gc \
    --gc-skew \
    --header-line \
    --only-id \
    "${file_longestcds}" \
    > "tmp.cds_length.tsv"

  if [[ -s "tmp.cds_length.tsv" ]]; then
    echo "Output file detected for the task: ${task}"
    mv_out "tmp.cds_length.tsv" "${file_longestcds_fx2tab}"
  fi
else
  gg_step_skip "${task}"
fi

task="MMseqs2 Taxonomy of the CDS sequences"
invalidate_cached_query_table_if_prefix_mismatch "${file_longestcds_mmseqs2taxonomy}" "${sp_ub}_" "${task}" 0
disable_if_no_input_file "run_longestcds_mmseqs2taxonomy" "${file_longestcds}"
if [[ ! -s "${file_longestcds_mmseqs2taxonomy}" && ${run_longestcds_mmseqs2taxonomy} -eq 1 ]]; then
  gg_step_start "${task}"

  if ! ensure_mmseqs_uniref90_db "${dir_mmseqs2_db}" "${GG_TASK_CPUS}"; then
    echo "Failed to prepare MMseqs2 UniRef90 DB. Exiting."
    exit 1
  fi

  if [[ ! -s "queryDB" ]]; then
    mmseqs createdb "${file_longestcds}" queryDB
  fi

  if [[ ! -e "tmp_mmseqs2" ]]; then
    mkdir -p "tmp_mmseqs2"
  fi

  mmseqs taxonomy "queryDB" "${dir_mmseqs2_db}/UniRef90_DB" "output_prefix" "tmp" \
    --split-mode 2 \
    --split-memory-limit "$(gg_memory_fraction_gb "${GG_MEM_TOOL_GB}" 3 4)G" \
    --majority 0.5 \
    --lca-mode 3 \
    --vote-mode 1 \
    --tax-lineage 2 \
    --orf-filter 0 \
    --threads "${GG_TASK_CPUS}"

  mmseqs createtsv "queryDB" "output_prefix" "result.tsv" --threads "${GG_TASK_CPUS}"

  if [[ -s "result.tsv" ]]; then
    echo "Output file detected for the task: ${task}"
    mv_out "result.tsv" "${file_longestcds_mmseqs2taxonomy}"
    rm -f -- queryDB*
    rm -f -- output_prefix.*
    rm -rf -- "tmp_mmseqs2"
  fi
else
  gg_step_skip "${task}"
fi

task="Contaminated sequence removal from the CDS sequences"
disable_if_no_input_file "run_longestcds_contamination_removal" "${file_longestcds}" "${file_longestcds_fx2tab}" "${file_longestcds_mmseqs2taxonomy}"
if [[ (! -s "${file_longestcds_contamination_removal_fasta}" || ! -s "${file_longestcds_contamination_removal_tsv}") && ${run_longestcds_contamination_removal} -eq 1 ]]; then
  gg_step_start "${task}"
  ensure_parent_dir "${file_longestcds_contamination_removal_fasta}"

  if ! ensure_ete_taxonomy_db "${gg_workspace_dir}"; then
    echo "Failed to prepare ETE taxonomy DB. Exiting."
    exit 1
  fi

  python "${gg_support_dir}/remove_contaminated_sequences.py" \
    --fasta_file "${file_longestcds}" \
    --mmseqs2taxonomy_tsv "${file_longestcds_mmseqs2taxonomy}" \
    --fx2tab_tsv "${file_longestcds_fx2tab}" \
    --species_name "${contamination_removal_target_taxon:-${sp_ub}}" \
    --rank "${contamination_removal_rank_for_remove_contaminated_sequences}" \
    --ncpu "${GG_TASK_CPUS}" \
    --rename_seq "no" \
    --verbose "no"

  if [[ -s "clean_sequences.fa" && -s "lineage_compatibility.tsv" ]]; then
    echo "Output file detected for the task: ${task}"
    seqkit seq --threads "${GG_TASK_CPUS}" "clean_sequences.fa" --out-file "tmp.longestcds.clean.fa.gz"
    mv_out "tmp.longestcds.clean.fa.gz" "${file_longestcds_contamination_removal_fasta}"
    rm -f -- "clean_sequences.fa"
    mv_out "lineage_compatibility.tsv" "${file_longestcds_contamination_removal_tsv}"
  fi
else
  gg_step_skip "${task}"
fi

task='BUSCO for cDNA isoforms (isoform.fasta)'
disable_if_no_input_file "run_busco_isoforms" "${file_isoform}"
if [[ (! -s "${file_busco_full_cdna_isoforms}" || ! -s "${file_busco_short_cdna_isoforms}") && ${run_busco_isoforms} -eq 1 ]]; then
  gg_step_start "${task}"
  busco_stage_status=0

  seqkit seq --threads "${GG_TASK_CPUS}" "${file_isoform}" --out-file "busco_infile_cdna.fa"

  if ! resolve_busco_lineage_for_current_species; then
    exit 1
  fi
  if ! dir_busco_db=$(ensure_busco_download_path "${gg_workspace_dir}" "${busco_lineage_resolved}"); then
    echo "Failed to prepare BUSCO dataset: ${busco_lineage_resolved}"
    exit 1
  fi
  dir_busco_lineage="${dir_busco_db}/lineages/${busco_lineage_resolved}"

  set +e
  run_busco_with_capture "cdna_isoforms" "busco_infile_cdna.fa"
  busco_stage_status=$?
  set -e
  if [[ ${busco_stage_status} -eq 10 ]]; then
    echo "Skipping BUSCO outputs for cDNA isoforms because BUSCO hit the known MetaEuk transcriptome bug."
    cleanup_busco_stage_temp_artifacts "busco_infile_cdna.fa"
    echo "$(date): End: ${task}"
  elif [[ ${busco_stage_status} -ne 0 ]]; then
    exit 1
  else
    if ! copy_busco_tables "./busco_tmp" "${busco_lineage_resolved}" "${file_busco_full_cdna_isoforms}" "${file_busco_short_cdna_isoforms}"; then
      echo "Failed to locate normalized BUSCO outputs for cDNA isoforms. Capturing repro artifacts."
      capture_busco_failure_context "cdna_isoforms" "busco_infile_cdna.fa" "./busco_tmp.stderr.log" || true
      echo "Failed to locate normalized BUSCO outputs for cDNA isoforms. Exiting."
      exit 1
    fi
    cleanup_busco_stage_temp_artifacts "busco_infile_cdna.fa"
    echo "$(date): End: ${task}"
  fi
else
  gg_step_skip "${task}"
fi

task='BUSCO for longest CDS'
disable_if_no_input_file "run_busco_longest_cds" "${file_longestcds}"
if [[ (! -s "${file_busco_full_longest_cds}" || ! -s "${file_busco_short_longest_cds}") && ${run_busco_longest_cds} -eq 1 ]]; then
  gg_step_start "${task}"
  busco_stage_status=0

  seqkit seq --threads "${GG_TASK_CPUS}" "${file_longestcds}" --out-file "busco_infile_cds.fa"

  if ! resolve_busco_lineage_for_current_species; then
    exit 1
  fi
  if ! dir_busco_db=$(ensure_busco_download_path "${gg_workspace_dir}" "${busco_lineage_resolved}"); then
    echo "Failed to prepare BUSCO dataset: ${busco_lineage_resolved}"
    exit 1
  fi
  dir_busco_lineage="${dir_busco_db}/lineages/${busco_lineage_resolved}"

  set +e
  run_busco_with_capture "longest_cds" "busco_infile_cds.fa"
  busco_stage_status=$?
  set -e
  if [[ ${busco_stage_status} -eq 10 ]]; then
    echo "Skipping BUSCO outputs for longest CDS because BUSCO hit the known MetaEuk transcriptome bug."
    cleanup_busco_stage_temp_artifacts "busco_infile_cds.fa"
    echo "$(date): End: ${task}"
  elif [[ ${busco_stage_status} -ne 0 ]]; then
    exit 1
  else
    if ! copy_busco_tables "./busco_tmp" "${busco_lineage_resolved}" "${file_busco_full_longest_cds}" "${file_busco_short_longest_cds}"; then
      echo "Failed to locate normalized BUSCO outputs for longest CDS. Capturing repro artifacts."
      capture_busco_failure_context "longest_cds" "busco_infile_cds.fa" "./busco_tmp.stderr.log" || true
      echo "Failed to locate normalized BUSCO outputs for longest CDS. Exiting."
      exit 1
    fi
    cleanup_busco_stage_temp_artifacts "busco_infile_cds.fa"
    echo "$(date): End: ${task}"
  fi
else
  gg_step_skip "${task}"
fi

task='BUSCO for contamination-removed longest CDS'
disable_if_no_input_file "run_busco_contamination_removed_longest_cds" "${file_longestcds_contamination_removal_fasta}"
if [[ (! -s "${file_busco_full_longest_cds_filtered}" || ! -s "${file_busco_short_longest_cds_filtered}") && ${run_busco_contamination_removed_longest_cds} -eq 1 ]]; then
  gg_step_start "${task}"
  busco_stage_status=0

  seqkit seq --threads "${GG_TASK_CPUS}" "${file_longestcds_contamination_removal_fasta}" --out-file "busco_infile_cds.fa"

  if ! resolve_busco_lineage_for_current_species; then
    exit 1
  fi
  if ! dir_busco_db=$(ensure_busco_download_path "${gg_workspace_dir}" "${busco_lineage_resolved}"); then
    echo "Failed to prepare BUSCO dataset: ${busco_lineage_resolved}"
    exit 1
  fi
  dir_busco_lineage="${dir_busco_db}/lineages/${busco_lineage_resolved}"

  set +e
  run_busco_with_capture "contamination_removed_longest_cds" "busco_infile_cds.fa"
  busco_stage_status=$?
  set -e
  if [[ ${busco_stage_status} -eq 10 ]]; then
    echo "Skipping BUSCO outputs for contamination-removed longest CDS because BUSCO hit the known MetaEuk transcriptome bug."
    cleanup_busco_stage_temp_artifacts "busco_infile_cds.fa"
    echo "$(date): End: ${task}"
  elif [[ ${busco_stage_status} -ne 0 ]]; then
    exit 1
  else
    if ! copy_busco_tables "./busco_tmp" "${busco_lineage_resolved}" "${file_busco_full_longest_cds_filtered}" "${file_busco_short_longest_cds_filtered}"; then
      echo "Failed to locate normalized BUSCO outputs for contamination-removed longest CDS. Capturing repro artifacts."
      capture_busco_failure_context "contamination_removed_longest_cds" "busco_infile_cds.fa" "./busco_tmp.stderr.log" || true
      echo "Failed to locate normalized BUSCO outputs for contamination-removed longest CDS. Exiting."
      exit 1
    fi
    cleanup_busco_stage_temp_artifacts "busco_infile_cds.fa"
    echo "$(date): End: ${task}"
  fi
else
  gg_step_skip "${task}"
fi

task='Assembly statistics'
disable_if_no_input_file "run_assembly_stat" "${file_isoform}"
if [[ "${run_longestcds}" -eq 1 ]]; then disable_if_no_input_file "run_assembly_stat" "${file_longestcds}"; fi
if [[ "${run_longestcds_contamination_removal}" -eq 1 ]]; then disable_if_no_input_file "run_assembly_stat" "${file_longestcds_contamination_removal_fasta}"; fi
if [[ ! -s "${file_assembly_stat}" && ${run_assembly_stat} -eq 1 ]]; then
  gg_step_start "${task}"

  input_files=("${file_isoform}")
  if [[ -s "${file_longestcds}" ]]; then
    input_files+=("${file_longestcds}")
  fi
  if [[ -s "${file_longestcds_contamination_removal_fasta}" ]]; then
    input_files+=("${file_longestcds_contamination_removal_fasta}")
  fi

  seqkit stats \
    --all \
    --tabular \
    --threads "${GG_TASK_CPUS}" \
    --out-file assembly_stat.tsv \
    "${input_files[@]}"

  if [[ -s assembly_stat.tsv ]]; then
    echo "The task ${task} was successful."
    mv_out assembly_stat.tsv "${file_assembly_stat}"
  fi
  echo "$(date): End: ${task}"
else
  gg_step_skip "${task}"
fi
