import importlib.util
import re
import shutil
import subprocess
from pathlib import Path

import pytest
from nwkit.convert import convert_tree_text

SCRIPT = Path(__file__).resolve().parents[1] / "support" / "mcmctree_time_scale.py"
SPEC = importlib.util.spec_from_file_location("mcmctree_time_scale", SCRIPT)
assert SPEC is not None
mcmctree_time_scale = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(mcmctree_time_scale)


def test_choose_scale_factor_keeps_calibration_ages_at_or_below_ten():
    tree = (
        "((a,b)'B(985,1392,0.025,0.025)',"
        "(c,d)'B(211.4155,370,0.025,0.025)');"
    )

    factor = mcmctree_time_scale.choose_scale_factor(
        tree,
        mcmctree_time_scale.Decimal("10"),
    )

    assert factor == mcmctree_time_scale.Decimal("1000")


def test_scale_calibration_labels_down_and_back_up_preserves_public_units():
    tree = (
        "((a,b)'B(985,1392,0.025,0.025)',"
        "(c,d)'L(211.4155,0.025,0.025)');"
    )

    scaled = mcmctree_time_scale.scale_calibration_labels(
        tree,
        mcmctree_time_scale.Decimal("1000"),
        "down",
    )
    restored = mcmctree_time_scale.scale_calibration_labels(
        scaled,
        mcmctree_time_scale.Decimal("1000"),
        "up",
    )

    assert "'B(0.985,1.392,0.025,0.025)'" in scaled
    assert "'L(0.2114155,0.025,0.025)'" in scaled
    assert "'B(985,1392,0.025,0.025)'" in restored
    assert "'L(211.4155,0.025,0.025)'" in restored


def test_genome_evolution_rebuilds_invalid_cached_mcmctree_without_reuse_fallback():
    core = (SCRIPT.parents[1] / "core" / "gg_genome_evolution_core.sh").read_text(
        encoding="utf-8"
    )

    validation = 'validate_mcmctree_figtree "${mcmctree_cached_tree}"'
    prepare = "gg_artifact_prepare_stage mcmctree_needs_update run_mcmctree2"
    assert core.index(validation) < core.index(prepare)
    assert 'case "${artifact_stale_policy:-stop}" in' in core[core.index(validation):core.index(prepare)]
    assert "stop|reuse)" in core[core.index(validation):core.index(prepare)]
    assert "mcmctree_needs_update=1" in core[core.index(prepare):]
    assert "run_mcmctree2=1" in core[core.index(prepare):]
    recovery = 'extract_scaled_mcmctree_figtree "${file_mcmctree_raw_output}" "${mcmctree_recovery_dir}/FigTree.tre" 1'
    assert core.index(validation) < core.index(recovery) < core.index(prepare)
    assert "Copying raw file instead" not in core


def test_scale_ctl_rootage_round_trips_public_units():
    ctl = "RootAge = <99.9 # generated by IQ2MC\nBDparas = 1 1 0.5\n"

    public_ctl = mcmctree_time_scale.scale_ctl_rootage_text(
        ctl,
        mcmctree_time_scale.Decimal("1000"),
        "up",
    )
    internal_ctl = mcmctree_time_scale.scale_ctl_rootage_text(
        public_ctl,
        mcmctree_time_scale.Decimal("1000"),
        "down",
    )

    assert "RootAge = <99900 # generated by IQ2MC" in public_ctl
    assert "RootAge = <99.9 # generated by IQ2MC" in internal_ctl


@pytest.mark.skipif(shutil.which("mcmctree") is None, reason="mcmctree is not installed")
def test_scaled_tree_runs_with_real_mcmctree_and_exports_public_units(tmp_path):
    public_tree = (
        "3 1\n"
        "((a,b)'B(985,1392,0.025,0.025)',c)'U(1500,0.025)';\n"
    )
    factor = mcmctree_time_scale.choose_scale_factor(
        public_tree,
        mcmctree_time_scale.Decimal("10"),
    )
    scaled_tree = mcmctree_time_scale.scale_calibration_labels(
        public_tree,
        factor,
        "down",
    )

    (tmp_path / "tree.nwk").write_text(scaled_tree, encoding="utf-8")
    (tmp_path / "dummy.phy").write_text(
        "3 4\n"
        "a    ACGT\n"
        "b    ACGT\n"
        "c    ACGT\n",
        encoding="utf-8",
    )
    (tmp_path / "mcmctree.ctl").write_text(
        "seed = 1\n"
        "seqfile = dummy.phy\n"
        "treefile = tree.nwk\n"
        "outfile = mcmctree.out\n"
        "mcmcfile = mcmc.txt\n"
        "ndata = 1\n"
        "seqtype = 0\n"
        "usedata = 0\n"
        "clock = 2\n"
        "RootAge = <1.5\n"
        "model = 4\n"
        "alpha = 0.5\n"
        "ncatG = 5\n"
        "cleandata = 1\n"
        "BDparas = 1 1 0.5 M\n"
        "kappa_gamma = 6 2\n"
        "alpha_gamma = 1 1\n"
        "rgene_gamma = 2 20 1\n"
        "sigma2_gamma = 1 10 1\n"
        "print = 1\n"
        "burnin = 10\n"
        "sampfreq = 2\n"
        "nsample = 10\n",
        encoding="utf-8",
    )

    completed = subprocess.run(
        ["mcmctree", "mcmctree.ctl"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
        timeout=20,
    )

    assert completed.returncode == 0, completed.stderr + "\n" + completed.stdout
    raw_output = (tmp_path / "mcmctree.out").read_text(encoding="utf-8")
    raw_figtree = convert_tree_text(raw_output, target="figtree")
    public_figtree = convert_tree_text(raw_output, target="figtree", time_factor=factor)
    raw_branch_lengths = [
        float(value)
        for value in re.findall(r":\s*([0-9]+(?:\.[0-9]+)?)", raw_figtree)
    ]
    branch_lengths = [
        float(value)
        for value in re.findall(r":\s*([0-9]+(?:\.[0-9]+)?)", public_figtree)
    ]
    raw_hpd_pairs = re.findall(r"95%HPD=\{([0-9.]+),\s*([0-9.]+)\}", raw_figtree)
    raw_hpd_values = [float(value) for pair in raw_hpd_pairs for value in pair]
    hpd_pairs = re.findall(r"95%HPD=\{([0-9.]+),\s*([0-9.]+)\}", public_figtree)
    hpd_values = [float(value) for pair in hpd_pairs for value in pair]

    assert public_figtree.startswith("#NEXUS")
    assert factor == mcmctree_time_scale.Decimal("1000")
    assert raw_branch_lengths
    assert max(branch_lengths) > 100
    assert max(branch_lengths) == pytest.approx(max(raw_branch_lengths) * float(factor))
    assert raw_hpd_values
    assert hpd_values
    assert max(hpd_values) == pytest.approx(max(raw_hpd_values) * float(factor))
    assert "B(0." not in public_figtree


@pytest.mark.parametrize('value', ['NaN', 'sNaN', 'Infinity', '-Infinity', '0', '-1'])
def test_time_scale_requires_finite_positive_number(value):
    import argparse

    with pytest.raises(argparse.ArgumentTypeError, match='positive'):
        mcmctree_time_scale.parse_scale(value)


@pytest.mark.parametrize('value', ['NaN', 'Infinity'])
def test_nonfinite_calibration_age_is_rejected(value):
    with pytest.raises(ValueError, match='finite'):
        mcmctree_time_scale.choose_scale_factor(f"(a,b)'U({value})';", mcmctree_time_scale.Decimal(10))
